name: Test AMDShark

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test-AMDShark:
    strategy:
      matrix:
        version: [3.11]
        os: [nodai-amdgpu-mi250-x86-64]

    runs-on: ${{matrix.os}}
    steps:
      - name: "Setting up Python"
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: ${{matrix.version}}

      - name: "Checkout AMDShark"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: "nod-ai/AMDShark.git"
          path: AMDShark
          ref: "main"

      - name: "Checkout iree-turbine"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: iree-org/iree-turbine
          # TODO: Let the ref be passed as a parameter to run integration tests.
          path: iree-turbine

      # TODO: Replace with a sh script from AMDShark repo
      - name: "Install AMDShark"
        run: |
          cd $GITHUB_WORKSPACE/AMDShark
          python${{ matrix.version }} -m venv AMDShark.venv
          source AMDShark.venv/bin/activate
          pip install -r requirements.txt --no-cache-dir
          pip install -e .
          python apps/AMDShark_studio/tests/api_test.py
