name: Test AMDShark

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test-AMDShark:
    strategy:
      matrix:
        version: [3.11]
        os: [nodai-amdgpu-mi250-x86-64]

    runs-on: ${{matrix.os}}
    steps:
      - name: "Setting up Python"
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version: ${{matrix.version}}

      - name: "Checkout AMD-Shark"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: "nod-ai/AMD-Shark.git"
          path: AMD-Shark
          ref: "main"

      - name: "Checkout iree-turbine"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: iree-org/iree-turbine
          # TODO: Let the ref be passed as a parameter to run integration tests.
          path: iree-turbine

      # TODO: Replace with a sh script from AMDShark repo
      - name: "Install AMDShark"
        run: |
          cd $GITHUB_WORKSPACE/AMDShark
          python${{ matrix.version }} -m venv AMDShark.venv
          source AMDShark.venv/bin/activate
          pip install -r requirements.txt --no-cache-dir
          pip install -e .
          python apps/AMDShark_studio/tests/api_test.py
